import Link from "next/link";
import CtaSection from "@/components/CtaSection";

const principles = [
  {
    number: "01",
    headline: "The clinician decides. Always.",
    body: "PsynapseMD structures your dictation into a draft note. That draft becomes final documentation only after you review, edit, and explicitly attest to it. The AI generates; the clinician decides. No exceptions.",
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
  },
  {
    number: "02",
    headline: "Patient data is never used to train AI.",
    body: "Data processed through PsynapseMD — session dictations, generated notes, patient information — is used solely to produce and store your clinical documentation. It is never fed into AI training pipelines, sold to third parties, or used for any purpose beyond the service itself.",
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
      </svg>
    ),
  },
  {
    number: "03",
    headline: "The AI documents. It does not diagnose.",
    body: "PsynapseMD is a documentation tool. It structures what you dictate — it does not interpret clinical findings, suggest diagnoses, recommend treatments, or guide clinical judgment. Your expertise is the input. The tool organizes the output.",
    icon: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
];

const dataItems = [
  {
    label: "What we collect",
    detail: "Session dictations, generated note content, and account information necessary to operate the service.",
  },
  {
    label: "How it's used",
    detail: "Solely to generate, display, and store clinical documentation within your account.",
  },
  {
    label: "What it's never used for",
    detail: "Training or improving AI models. Selling or sharing with third parties. Advertising or analytics beyond service operation.",
  },
  {
    label: "How it's protected",
    detail: "HIPAA-compliant Microsoft Azure infrastructure. Encrypted in transit and at rest. Business Associate Agreements (BAAs) in place as required.",
  },
  {
    label: "Retention",
    detail: "Data retention terms are defined in your service agreement. You retain ownership of your clinical documentation at all times.",
  },
];

const governanceItems = [
  {
    headline: "Formal AI governance framework",
    body: "PsynapseMD was developed under a structured AI governance framework — incorporating transparency, accountability, and human oversight from design through deployment. Governance is not audited after the fact; it is built into the process.",
  },
  {
    headline: "Clinician attestation as a control",
    body: "Every note generated by PsynapseMD requires explicit review and attestation by a licensed clinician before it is stored as a finalized record. Attestation is a workflow requirement, not an optional step.",
  },
  {
    headline: "Auditability",
    body: "All finalized notes are clinician-attested and logged. Records are structured to support payer audits, clinical review, and compliance inquiries — without scrambling to reconstruct documentation after the fact.",
  },
  {
    headline: "Non-clinical scope",
    body: "PsynapseMD is classified as a documentation support tool, not a diagnostic or treatment device. It does not provide clinical recommendations, interpret symptom data, or substitute for clinical judgment at any point in the workflow.",
  },
];

export default function ResponsibleUsePage() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden bg-[#F7F6F2] min-h-[50vh] flex items-center">
        <div
          aria-hidden="true"
          className="absolute -top-20 -right-20 w-96 h-96 rounded-full bg-[#E8F5F3] opacity-60 blur-3xl pointer-events-none"
        />
        <div
          aria-hidden="true"
          className="absolute top-40 -right-10 w-64 h-64 rounded-full border-2 border-[#0A7C6E] opacity-10 pointer-events-none"
        />
        <div className="max-w-6xl mx-auto px-6 py-24 relative z-10">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 bg-[#E8F5F3] text-[#0A7C6E] text-xs font-semibold px-3 py-1.5 rounded-full mb-6 uppercase tracking-wide">
              Responsible Use
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-[#111827] leading-tight mb-6 font-[family-name:var(--font-jakarta)]">
              Ethics isn&apos;t a feature.<br className="hidden md:block" /> It&apos;s the foundation.
            </h1>
            <p className="text-xl text-[#4B5563] leading-relaxed max-w-2xl">
              PsynapseMD was designed from the start with clinician ethics, patient protection, and AI accountability at its center. This page explains how — plainly.
            </p>
          </div>
        </div>
      </section>

      {/* Core Principles */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl md:text-4xl font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">
            Core Principles
          </h2>
          <p className="text-[#4B5563] text-lg mb-12">
            Three commitments that are non-negotiable in how this product is built and operated.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {principles.map((p) => (
              <div key={p.number} className="border border-[#E5E3DC] rounded-2xl p-8 bg-[#F7F6F2]">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-9 h-9 rounded-full bg-[#E8F5F3] flex items-center justify-center text-[#0A7C6E]">
                    {p.icon}
                  </div>
                  <span className="text-[10px] font-bold text-[#0A7C6E] uppercase tracking-[0.3em]">{p.number}</span>
                </div>
                <h3 className="text-lg font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">{p.headline}</h3>
                <p className="text-[#4B5563] leading-relaxed text-sm">{p.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How the AI Works */}
      <section className="py-20 bg-[#F7F6F2]">
        <div className="max-w-6xl mx-auto px-6">
          <div className="max-w-3xl">
            <h2 className="text-3xl md:text-4xl font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">
              How the AI Works
            </h2>
            <p className="text-[#4B5563] text-lg mb-10">
              Transparency about what the model does — and doesn&apos;t do — at every step.
            </p>
            <div className="space-y-0">
              {[
                {
                  step: "Input",
                  desc: "You dictate your clinical observations after the session — freeform, in your own words, same as any transcription tool.",
                },
                {
                  step: "Process",
                  desc: "A large language model structures your dictation against treatment-specific documentation templates for ketamine, TMS, or Spravato. It organizes language; it does not interpret or evaluate clinical content.",
                },
                {
                  step: "Output",
                  desc: "A complete draft note is presented for your review. Every field is editable. Nothing is pre-approved.",
                },
                {
                  step: "Finalization",
                  desc: "The note becomes final documentation only after your explicit review, editing, and attestation. No note is stored as final without your approval.",
                },
              ].map((item, i, arr) => (
                <div key={item.step} className={`flex gap-6 ${i < arr.length - 1 ? "pb-8 border-b border-[#E5E3DC]" : ""} ${i > 0 ? "pt-8" : ""}`}>
                  <div className="flex-shrink-0">
                    <div className="w-20 text-[10px] font-bold text-[#0A7C6E] uppercase tracking-[0.2em] pt-0.5">{item.step}</div>
                  </div>
                  <p className="text-[#4B5563] leading-relaxed">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Data Policy */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl md:text-4xl font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">
            Data Policy
          </h2>
          <p className="text-[#4B5563] text-lg mb-12">
            Plain-language summary. Full terms are in your service agreement.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-[#E5E3DC] border border-[#E5E3DC] rounded-2xl overflow-hidden">
            {dataItems.map((item) => (
              <div key={item.label} className="bg-white p-8">
                <p className="text-[10px] font-bold text-[#0A7C6E] uppercase tracking-[0.3em] mb-3">{item.label}</p>
                <p className="text-[#4B5563] leading-relaxed text-sm">{item.detail}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* AI Governance */}
      <section className="py-20 bg-[#F7F6F2]">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl md:text-4xl font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">
            AI Governance
          </h2>
          <p className="text-[#4B5563] text-lg mb-12">
            Accountability structures that govern how PsynapseMD is built and deployed.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {governanceItems.map((item) => (
              <div key={item.headline} className="border border-[#E5E3DC] rounded-2xl p-8 bg-white">
                <h3 className="text-base font-bold text-[#111827] mb-3 font-[family-name:var(--font-jakarta)]">{item.headline}</h3>
                <p className="text-[#4B5563] leading-relaxed text-sm">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Questions */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <div className="max-w-2xl">
            <h2 className="text-3xl font-bold text-[#111827] mb-4 font-[family-name:var(--font-jakarta)]">
              Questions about data or governance?
            </h2>
            <p className="text-[#4B5563] leading-relaxed text-lg mb-8">
              If you have questions about how PsynapseMD handles patient data, operates its AI, or meets compliance requirements, reach out directly. We will give you a straight answer.
            </p>
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 text-[#0A7C6E] font-semibold hover:gap-3 transition-all"
            >
              Contact us
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
          </div>
        </div>
      </section>

      <CtaSection
        headline="See it in your practice."
        body="Every setup starts with a consultation. We answer your questions before any clinical use begins."
        buttonText="Request a Demo"
        href="/contact"
      />
    </>
  );
}
